apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e64ukhksu-python
  janus-idp.io/tekton: e64ukhksu-python
  backstage.io/kubernetes-id: e64ukhksu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e64ukhksu-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
